### PR TITLE
增加了Claude 3模型的访问

### PR DESCRIPTION
**Pull request by ChenYuZe519**
Added access to Claude 3 model

### CODE REVIEW

**Comment by ChenYuZe519** [comment]
New Chat

**Comment by singhfinity** [comment]
This is incorrect, you have to use the messages API endpoint that Anthropic provides.

**Comment by ChenYuZe519** [comment]
> This is incorrect, you have to use the messages API endpoint that Anthropic provides.

The intermediary endpoint for the API is not necessary, as most people are using inexpensive intermediary endpoints. If you need to add the Anthropic API interface, do it yourself in src/constants/auths.ts and src/store/migrate.ts.

Additionally, the final interface of this project supports custom endpoints on its own, so what exactly are you doing? Go figure it out first.

**Comment by ChenYuZe519** [comment]
> This is incorrect, you have to use the messages API endpoint that Anthropic provides.

The official Claude API endpoint is not necessary, as most people are using inexpensive intermediary endpoints. If you need to add the Anthropic API interface, do it yourself in src/constants/auths.ts and src/store/migrate.ts.

Additionally, the final interface of this project supports custom endpoints on its own, so what exactly are you doing? Go figure it out first.

**Comment by singhfinity** [comment]
Everything you just mentioned is silly. You haven't even modified the default list. That's not even the correct model name. This PR needs to be closed.
Refer to the correct model names here for Haiku, Sonnet and Opus:
https://docs.anthropic.com/claude/docs/models-overview

System is separate from the messages field when using official anthropic inference point.
This is clearly half-assed.

**Comment by ChenYuZe519** [comment]
> Everything you just mentioned is silly. You haven't even modified the default list. That's not even the correct model name. This PR needs to be closed. Refer to the correct model names here for Haiku, Sonnet and Opus: https://docs.anthropic.com/claude/docs/models-overview
> 
> System is separate from the messages field when using official anthropic inference point. This is clearly half-assed.



> Everything you just mentioned is silly. You haven't even modified the default list. That's not even the correct model name. This PR needs to be closed. Refer to the correct model names here for Haiku, Sonnet and Opus: https://docs.anthropic.com/claude/docs/models-overview
> 
> System is separate from the messages field when using official anthropic inference point. This is clearly half-assed.



> Everything you just mentioned is silly. You haven't even modified the default list. That's not even the correct model name. This PR needs to be closed. Refer to the correct model names here for Haiku, Sonnet and Opus: https://docs.anthropic.com/claude/docs/models-overview
> 
> System is separate from the messages field when using official anthropic inference point. This is clearly half-assed.

Your perspective appears to be misunderstood. I've reiterated that the recent modifications are intended for cost-effective API proxy endpoints, not Anthropic's official ones.Proxy endpoints commonly utilize the OpenAI interaction model, including Gemini and Qwen. Initially, these proxies did not support versioning for Opus calls, a deviation from the official API. Forcing a version number would lead to call failure. Recently, these sites began supporting version numbers, but since Opus can still be called successfully without them, and the project seems to have no plans to add models beyond OpenAI like Claude, this issue has not been updated.I am aware of your reference to using the endpoint provided by Anthropic. Indeed, the initial design of the project was to accommodate various API needs, whether official or intermediary. Given that most users opt for more affordable proxy endpoints, corresponding adjustments were made.We both contribute to this community out of a passion for the project. I appreciate your critique of this issue, indicating your interest in utilizing the project for Claude calls. However, further communication and understanding regarding implementation details are necessary. I've provided guidance on using official endpoints, yet, unfortunately, your manner of expression was rather inappropriate.As you wish, I will close this issue. Considering the project currently has no plans to support models outside of OpenAI and requires communication with individuals of low quality, closing this issue seems like the best course of action.

**Pull request closed without merging**
