### PR TITLE
Update api.ts

### PR DESCRIPTION
**Pull request by yfw918**
Update Azure API version. Sorry for closing PR by mistake earlier. 
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

### CODE REVIEW

**Review by ztjhz — APPROVED** [review]

**Comment by yfw918** [comment]
I've noticed that the newer API version have different return values than the older version, so other code changes may be needed, here are some examples:
api_version = '2023-05-15'：
{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "This is a response to your test. How can I assist you?",
        "role": "assistant"
      }
    }
  ],
  "created": 1699518695,
  "id": "chatcmpl-8IujnmYS386HmiSJp3U6cFy5uzs1L",
  "model": "gpt-35-turbo",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 14,
    "prompt_tokens": 8,
    "total_tokens": 22
  }
}

api_version = '2023-09-01-preview':
{
  "choices": [
    {
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      },
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "Hello! How can I assist you today?",
        "role": "assistant"
      }
    }
  ],
  "created": 1699518879,
  "id": "chatcmpl-8Iumlm9xpj8AXenBhdQ7o9qL9qLnp",
  "model": "gpt-35-turbo",
  "object": "chat.completion",
  "prompt_filter_results": [
    {
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      },
      "prompt_index": 0
    }
  ],
  "usage": {
    "completion_tokens": 9,
    "prompt_tokens": 8,
    "total_tokens": 17
  }
}

**Comment by yfw918** [comment]
@ztjhz An hour ago you updated api.ts and then Azure GPT4 doesn't work. It says: "Message from Better ChatGPT.
Invalid API endpoint! We recommend you to check your free API endpoint.". But I tested locally and the api is working fine.

**Comment by ztjhz** [comment]
@yfw918 A fix has been pushed. You can try to see if it is valid.

**Comment by yfw918** [comment]
> @yfw918 A fix has been pushed. You can try to see if it is valid.

Almost there, you missed a dash, I added it.

**Comment by yfw918** [comment]
> > @yfw918 A fix has been pushed. You can try to see if it is valid.
> 
> Almost there, you missed a dash, I added it.

**Review by ztjhz — APPROVED** [review]

**Pull request merged**
