### PR TITLE
Move low-frequency options to settings menu

### PR DESCRIPTION
**Pull request by solstice23**
- Move low-frequency options to settings menu
- ~~Add lockfiles to .gitignore~~
image
image

### CODE REVIEW

**Review by ayaka14732 — COMMENTED** [review]
感谢贡献！但是这个 PR 我认为不可以合并。首先，lockfiles 万万不能加入 `.gitignore`，因为 lockfiles 通常包含了项目所依赖的软件包的确切版本信息，这些信息对于其他开发者或部署环境非常重要。如果将 lockfiles 添加到 `.gitignore` 文件中，则它们将不会被包含在代码库中，这可能会导致其他开发者在克隆代码后无法正确地安装依赖关系，或者在部署时出现不可预测的问题。相反，应该将 lockfiles 包含在版本控制系统中，并确保在部署时使用正确的锁定文件来保证在部署环境中使用与开发环境中相同的软件包版本。这可以通过使用类似于 `npm ci` 或 `yarn install --frozen-lockfile` 的命令来实现，这些命令将使用锁定文件不变地安装依赖项。

其次，我认为 Light Mode 不应该加入侧边栏中，因为用户通常只会使用一种，不会一直更改这个设定。导入/导出我认为维持现在放置在侧边栏上的状态比较合适。

Thanks for your contribution! However, I don't think this PR should be merged. First of all, lockfiles should never be added to `.gitignore` because lockfiles typically contain the exact version information of the software packages that the project depends on, which is crucial for other developers or deployment environments. If lockfiles are added to the `.gitignore` file, they will not be included in the code repository, which may prevent other developers from installing dependencies correctly after cloning the code or lead to unpredictable problems during deployment. Instead, lockfiles should be included in the version control system and ensure that the correct lockfile is used during deployment to ensure the same software package versions are used in the deployment environment as in the development environment. This can be achieved by using commands such as `npm ci` or `yarn install --frozen-lockfile`, which will install dependencies immutably using the lockfile.

Secondly, I don't think Light Mode should be added to the sidebar because users usually only use one mode and don't constantly change this setting. I believe that Import/Export should remain in the current sidebar position, which is more appropriate.

**Comment by solstice23** [comment]
Thank you for the reminder. I have reverted the .gitignore change and moved the theme switcher to the settings menu. However, there was a new `package-lock.json` generated because I used npm. Should I delete this file?

**Comment by ztjhz** [comment]
You should not include `package-lock.json` in the commit.

**Comment by ztjhz** [comment]
The cursor for the `import/export` and `clear conversation` buttons is not pointer. Add `cursor-pointer` to their className.

image

**Comment by SamuelMiller** [comment]
As "Clear Conversation" and "Import/Export" both pertain to managing the chat history, whether by clearing, exporting, or importing, it is appropriate for them to be kept (grouped) together either in the sidebar or as a submenu under the settings.

**Comment by solstice23** [comment]
> As "Clear Conversation" and "Import/Export" both pertain to managing the chat history, whether by clearing, exporting, or importing, they should, in my opinion, be kept (grouped) together, not separated, whether they are placed in the sidebar menu or in the settings submenu.

They have already moved to the settings menu.

**Comment by SamuelMiller** [comment]
With the new foldable menu feature for the settings in the latest BetterChatGPT, I don't think we need to move the low-frequency options as the user can simply just collapse the menu to make more space for the chat history.  My original request offered two suggested solutions to make more room for the settings. Now with the collapsable menu feature my request has been fulfilled.

**Pull request closed without merging**
